USE PizzaNet;
GO

CREATE TABLE Clientes(
	Id INT IDENTITY NOT NULL,
	Nombre VARCHAR NOT NULL,
	Direccion VARCHAR(100) NOT NULL,
	Tlfno CHAR(9) NOT NULL,
	Ecorreo VARCHAR(100) NOT NULL
	CONSTRAINT PkCliente PRIMARY KEY (Id),
	CONSTRAINT UTlfnoCliente UNIQUE(Tlfno)
)
